version: "3.0"
services:
  guessinggame:
    build: 
      context: .
      dockerfile: Dockerfile
    image: ggimage
    container_name: guessinggame
    ports:
      - 5000:5000
      - 5001:5001
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: "https://+:5001;http://+:5000"
      TZ: Europe/Oslo
